### PR TITLE
Correctly parse complex objects

### PR DESCRIPTION
**Pull request by cibernox**
I've found recently that route-recognizer doesn't have any support for object encoded in the URL.

Example using Ember:

Doing `store.query('foo', { filter: { name: 'John' } })` the generated URL (probably using `$.params` inside) looks like this `/foos?filter%5Bname%5D=John`.

However, route-recognizer is fed with this url, parses this `{ "filter[name]": "John" }` instead of 
`{ filter: { name: 'John' } }`.

I consider this a bug, since [$.deparam](https://github.com/AceMetrix/jquery-deparam) works as expected, and in the backend Rack also works as expected

``` rb
Rack::Utils.parse_nested_query("filter%5Bname%5D=John") #=> {"filter"=>{"name"=>"John"}}
```

This adds a failing test. I'll try to tackle this myself later today.

### CODE REVIEW

**Comment by cibernox** [comment]
Fixed.

I basically copied $.deparam and added a couple tweaks to match the current behaviour:
* use `decodeQueryParamPart` instead of `decodeURIComponent` to not break on malformed URLs
* Coerce key-only params to `true` instead of undefined.
* Removed coercion of numbers/'null'/'undefined'/'true'/'false' to the real values. I actually think that this would be a nice feature, but is certainly breaking.
* Use the `isArray` method defined in the same file.
* Fixed code styles to be aligned with the rest of the file (no spaces around parens, no linebreaks on ternary operators, ect...)

Open questions:
*I left the code comments present in the original code. Should I remove them? I found them helpful to understand the algorithm.
* Should I leave a comment giving credit to the implementation I stole from?
* I fixed on failing test that was actually asserting precisely the wrong behaviour I wanted to fix with the PR. This bugfix should increment a middle number?

**Comment by nathanhammond** [comment]
Any decision here is based upon server implementation. route-recognizer is a server-agnostic, client-framework agnostic micro-library. Perfection for this is impossible: fix it for one, break it for another. I honestly believe that route-recognizer should lose opinions here and make the function easily pluggable. For LinkedIn we wrote our own BNF parser for serializing and deserializing our object format. With that as my reference point I'm of the opinion that we should probably do the dumbest thing possible in route-recognizer by default:

```javascript
/* ... */
  QPSerializer(querystring) {
    return querystring.split('&').map((kvpair) => {
      var result = {};
      [result.key, result.value] = kvpair.split('=');
      return result;
    });
  }
/* ... */
var serialize = options.serialize || this.QPSerializer;
serialize(location.search);
```

Even unescaping can be dangerous, as proven by @bantic. [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) doesn't specify many opinions about how to serialize/deserialize querystrings.

**Comment by cibernox** [comment]
This wasn't actually driven by any backend implementation, I just added the Rack example for completeness.

I'm totally into the idea of allowing people to customize how query params are parsed, but I don't see why the default implementation has to be the naivest one possible. 

I ran into this because I expected route-recognizer to understand a query string generated by `$.ajax` and it didn't. 

I get that jQuery does not posses the absolute truth about coding/decoding query params, but it is almost ubiquitous and where it is not present chances are library is used is inspired by it and `$.param`, so mimic `$.deparam` seemed a very reasonable default. The existing implementation was already very very close, just this case was different.

If there we implement a very naive parsing algorithm, I do think that Ember as a batteries-included framework should customize it with a more complex default.

**Comment by nathanhammond** [comment]
I've come around a bit on this. I feel like we should implement the inverse of `$.param` as the defacto standard of query parameter serialization. It's also very close to what we presently have.

I still believe that it should be exposed as something which is configurable by the consumer.

**Comment by cibernox** [comment]
This is exactly that (assuming the well-know `$.deparam` is the right inverse of `$.param`).

However, since this PR wasn't merged back when I needed it, I implemented this behaviour in app-land, and if this becomes the default now it will be a breaking change for my app and possibly many others.

I think that being able to configure how query strings are parsed has to come first, then users can opt in to the new `$.deparam` function (or create their own), and eventually this can be updated in Ember 3.0.0.

Another thought on the matter: Ember-cli-mirage is a very popular addon that uses r-r to match urls handlers in the fake server. It doesn't bundle r-r, but uses whatever version ships with ember. The param parser function should be configurable on a per-instance of r-r basis, so the ember-app can use one, and your mirage instance can use another that is more convenient for your usage. By example if your backend is rails, or python, you might want to configure the parse function to behave the same way the one in your backend behaves.

**Comment by nathanhammond** [comment]
Unfortunately `jQuery.param` has unaccounted for edge cases:

```js
decodeURIComponent(
  $.param(
    { b: {'a][something': 'collision', 'a':{ something: 'collision'}}}
  )
);
// => b[a][something]=collision&b[a][something]=collision
```

I really don't like standardizing on an encoding that is guaranteed lossy and possible to troll our users. More thinking required.

**Comment by cibernox** [comment]
Actually ...

screen shot 0028-08-21 at 10 08 36

**Comment by nathanhammond** [comment]
Dunno what's going on for you:
screen shot 2016-08-21 at 2 11 51 am

**Comment by cibernox** [comment]
Ok, I've just opened a random page I was on and tried that. Probably the version of jQuery was ancient.

**Comment by nathanhammond** [comment]
https://github.com/jquery/jquery/issues/3286

**Comment by wagenet** [comment]
Closing due to staleness.

**Pull request closed without merging**
