### PR TITLE
Prevent clobbering of existing named routes.

### LINKED ISSUE #117: Clobbering inside of `names` object.
```javascript
router.add([{ path: "/posts/:id/foo", handler: "post" }], { as: "post" });
router.add([{ path: "/posts/:id", handler: "post" }], { as: "post" });
```

This puts two routes into the NFA and one route into the `names` object by virtue of clobbering. Lookup by name will thus return the second route. However, `router.recognize('/posts/12/foo')` will still actually match and return the handler specified for the first route as it still exists in the NFA.

We should stop allowing you to clobber keys in the `names` object.

@wycats @rwjblue @krisselden @mixonic Confirm that this should be considered a bug?

/cc @trentmwillis

### PR DESCRIPTION
**Pull request by nathanhammond**
Closes #117.

### CODE REVIEW

**Comment by nathanhammond** [comment]
This is complete. Assuming no further comments I intend to land it sometime this weekend. Review now! /cc @wycats @krisselden @mixonic @rwjblue 

Note: landing doesn't mean an immediate release, I intend to make sure that this goes the full span of an Ember canary to get as much feedback as possible on how often people end up broken.

**Comment by trek** [comment]
I _think_ this will break Pretender, which allows people to define the same route a second time for two use cases:

### First, people store up map sets:

```
// user-maps.js
export default function(){
  this.post('/sign-in', function() {...});
  this.get('/profile', function() {...});

 ... 10 more routes ...
}
```

And then override them in tests where a specific behavior is desired:

```
// some test:

import userMaps from 'user-maps';
let overrideProfile = function() {
  this.get('/profile', function(){
    return [404, {}, ''];
  };
};


test('display missing profile page if authenticated user does not have a profile', function(){
  let server = new Pretender;
  server.map(userMaps);
  server.map(overrideProfile);
})
```

Here, `/profile` is defined twice. Once for _most_ cases, and then a more specific version is supplied for a specific case.

### Second, define a route twice in one test to test behaviors where subsequent requests to a route need new responses:

```
test('a request to paginated collections that are out of bounds returns an empty collection', function(){
 
 let server = new Pretender();
 server.map(function(){
   this.get('/books', function() {
      return [200, {}, "[{}, {}, {}]"];
    });
  });
  
  ajax.get(page one of books)
  assert(...);
  
   server.map(function(){
   this.get('/books', function() {
      return [200, {}, "[]"];
    });
  });

  ajax.get(page two of books, which is empty)
  assert(...);
})
```

Both can be done in other ways, but I've seen both use cases and this change would be breaking from that perspective and would require a SemVer bump

**Comment by nathanhammond** [comment]
@trek Taking this, for example:

> `server.map(overrideProfile);` Here, `/profile` is defined twice. Once for most cases, and then a more specific version is supplied for a specific case.

I'm not sure that you're actually naming these routes in Pretender. This only prevents you from calling `router.generate` for a duplicate named route. If you manage to get it into the NFA (which you can do without naming it) then it will still appropriately recognize. The only trick is that I don't know how you patch into the DSL and it's possible that you're depending on definition order doing the "right" thing which is `undefined` behavior. (Like most of this was.)

Regardless, I will run Pretender's test suite against this change and see–I assume you have test cases for this behavior? I still want for this to be an error in route-recognizer and if Pretender is relying on this behavior I'll make sure to have an ergonomic API proposal (or possibly a PR which makes it work with no change to Pretender's API).

**Comment by nathanhammond** [comment]
@trek's note has now been confirmed to be a non-issue. Additional tests in place to help us monitor Pretender for regressions.

**Comment by nathanhammond** [comment]
Given no additional feedback for two weeks, I'm landing this.

**Pull request merged**
